ALTER DEFAULT PRIVILEGES IN SCHEMA catalog REVOKE SELECT ON TABLES FROM PUBLIC;
REVOKE SELECT ON ALL TABLES IN SCHEMA catalog FROM PUBLIC;
REVOKE USAGE ON SCHEMA catalog FROM PUBLIC;

ALTER DEFAULT PRIVILEGES IN SCHEMA sales REVOKE USAGE, SELECT ON SEQUENCES FROM sales_manager;
ALTER DEFAULT PRIVILEGES IN SCHEMA sales REVOKE ALL ON TABLES FROM sales_manager;
REVOKE USAGE, SELECT ON ALL SEQUENCES IN SCHEMA sales FROM sales_manager;
REVOKE ALL ON ALL TABLES IN SCHEMA sales FROM sales_manager;
REVOKE USAGE ON SCHEMA sales FROM sales_manager;

ALTER DEFAULT PRIVILEGES IN SCHEMA catalog REVOKE USAGE, SELECT ON SEQUENCES FROM catalog_manager;
ALTER DEFAULT PRIVILEGES IN SCHEMA catalog REVOKE ALL ON TABLES FROM catalog_manager;
REVOKE USAGE, SELECT ON ALL SEQUENCES IN SCHEMA catalog FROM catalog_manager;
REVOKE ALL ON ALL TABLES IN SCHEMA catalog FROM catalog_manager;
REVOKE USAGE ON SCHEMA catalog FROM catalog_manager;
